resources:
  - ../default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: jfrog-token-exchanger-config
  envs:
  - ./jfrog.env

images:
- name: ghcr.io/richardmsong/jfrog-token-exchanger
  newTag: pr-8